name: Salmon Statsの記録のアップデート

on:
  push:
    branches:
      - salmonstats
  schedule:
    - cron: "*/10 * * * *"

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python # Pythonのセットアップ
        uses: actions/setup-python@v2
        with:
          python-version: "3.9" # Pythonのバージョン指定

      - name: Install dependencies # 依存パッケージのインストール
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run main.py # PythonでAPIからデータ取得
        run: |
          python main.py

      - name: Commit and Push # 実行結果をプッシュしてレポジトリに反映
        run: |
          git config --local user.email "nasawake.am@gmail.com"
          git config --local user.name "tkgstrator"
          git pull
          if (git diff --shortstat | grep '[0-9]'); then \
            git add .; \
            git commit -m "Salmon Statsの記録をアップデート"; \
            git push origin salmonstats; \
          fi
